version: '3'
services:
  web:
    container_name: web
    image: shinjeongsub/hufsmeals-prod
    restart: always
    expose:
      - "8080"
      - "8080:8080"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/certbot/conf:/etc/letsencrypt
      - ./cert/certbot/www:/var/www/certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
